spring:
  application:
    name: isc
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/views/freemarker
    cache: false
  resources:
    static-locations: classpath:/static

server:
  port: 9000

isc:
  database:
    mongodb:
      host: 127.0.01
      port: 27017
      username: admin
      password: 123456
      database-name: isc
